### PR TITLE
allow uploading same file twice

### PR DESCRIPTION
**Pull request by csulok**
The input field needs to be cleared to allow selecting and uploading the same file again. I've formed the suggestion from https://github.com/leon/angular-upload/issues/26 into a pull request. Could you review it?

### CODE REVIEW

**Comment by matt-major** [comment]
+1

@leon are you still actively supporting this project & in a position where you can merge this in?

**Comment by smikhailov** [comment]
+1
@leon It would be extremely helpful for us as well. The use case for uploading the same file name twice is valid. We were about to clone this, so we can update the bower files to install 'angular-upload' from a local repo. But if this the pull request can be merged and new bower package available, it will be very helpful to many.

Thanks.

**Comment by leon** [comment]
Sorry guys, I've been extremely busy at work. so no downtime for open source :)

**Comment by leon** [comment]
Now 1.0.12 is published to bower and npm

**Pull request merged**
